version: '3'

services:
  app:
    image: 'dinopedia:latest'
    build:
      context: .
    container_name: dinopedia
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresqldb:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    container_name: postgresql
    environment:
      - POSTGRES_DB=dinopedia
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin